name: Deploy NestJS Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t gablugap/easy-backend .

      - name: Publish Docker image to Docker Hub
        run: docker push gablugap/easy-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image from Docker Hub
        run: docker pull gablugap/easy-backend:latest

      - name: Stop old Docker container (if exists)
        run: docker stop gablugap-easy-backend-container || true

      - name: Delete old Docker container (if exists)
        run: docker rm -f gablugap-easy-backend-container || true

      - name: Run new Docker container
        run: docker run --rm --pull always -d -p 80:3001 --name gablugap-easy-backend-container gablugap/easy-backend:latest
