name: Deploy NestJS Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t gablugap/easy-backend:latest .

      - name: Publish Docker image to Docker Hub
        run: docker push gablugap/easy-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: List current Docker images before pull
        run: docker images

      - name: Pull Docker image from Docker Hub
        run: docker pull gablugap/easy-backend:latest

      - name: List Docker images after pull
        run: docker images

      - name: Stop old Docker container (if exists)
        run: docker stop gablugap-easy-backend-container || true

      - name: Delete old Docker container (if exists)
        run: docker rm -f gablugap-easy-backend-container || true

      - name: Remove old Docker image (if exists)
        run: docker rmi gablugap/easy-backend:latest || true

      - name: Run new Docker container with environment variables
        run: |
          docker run  --pull always -d -p 80:3001 --name gablugap-easy-backend-container -e PORT=${{ secrets.PORT }} -e FRONTEND_URL=${{ secrets.FRONTEND_URL }} -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e MONGODB_URI=${{ secrets.MONGODB_URI }} gablugap/easy-backend:latest

      - name: List running Docker containers
        run: docker ps
